export const FETCH_DATA = 'FETCH_DATA';

export const FETCH_UNIVERSES_START = 'FETCH_UNIVERSES_START';
export const FETCH_UNIVERSES_SUCCESS = 'FETCH_UNIVERSES_SUCCESS';
export const FETCH_UNIVERSES_FAIL = 'FETCH_UNIVERSES_FAIL';

export const FETCH_UNIVERSE_START = 'FETCH_UNIVERSE_START';
export const FETCH_UNIVERSE_SUCCESS = 'FETCH_UNIVERSE_SUCCESS';
export const FETCH_UNIVERSE_FAIL = 'FETCH_UNIVERSE_FAIL';

export const FETCH_STARS_START = 'FETCH_STARS_START';
export const FETCH_STARS_SUCCESS = 'FETCH_STARS_SUCCESS';
export const FETCH_STARS_FAIL = 'FETCH_STARS_FAIL';

export const GET_UNIVERSES_START = 'GET_UNIVERSES_START';
export const GET_UNIVERSES_SUCCESS = 'GET_UNIVERSES_SUCCESS';
export const GET_UNIVERSES_FAIL = 'GET_UNIVERSES_FAIL';

export const POST_UNIVERSE_START = 'POST_UNIVERSE_START';
export const POST_UNIVERSE_SUCCESS = 'POST_UNIVERSE_SUCCESS';
export const POST_UNIVERSE_FAIL = 'FETCH_UNIVERSE_POST';

export const GET_STARS_START = 'GET_STARS_START';
export const GET_STARS_SUCCESS = 'GET_STARS_SUCCESS';
export const GET_STARS_FAIL = 'GET_STARS_FAIL';



export const DELETE_STAR_SUCCESS = 'DELETE_STAR_SUCCESS';
export const DELETE_STAR_FAIL = 'DELETE_STARS_FAIL';

export const CLICK_BUTTON = 'CLICK_BUTTON';
export const RECV_ERROR = 'RECV_ERROR';
export const REQ_DATA = 'REQ_DATA';
export const RECV_DATA = 'RECV_DATA';