export const GET_UNIVERSES_START = 'GET_UNIVERSES_START';
export const GET_UNIVERSES_SUCCESS = 'GET_UNIVERSES_SUCCESS';
export const GET_UNIVERSES_FAIL = 'GET_UNIVERSES_FAIL';

export const POST_UNIVERSE_START = 'POST_UNIVERSE_START';
export const POST_UNIVERSE_SUCCESS = 'POST_UNIVERSE_SUCCESS';
export const POST_UNIVERSE_FAIL = 'FETCH_UNIVERSE_POST';

export const GET_STARS_START = 'GET_STARS_START';
export const GET_STARS_SUCCESS = 'GET_STARS_SUCCESS';
export const GET_STARS_FAIL = 'GET_STARS_FAIL';

export const POST_STAR_START = 'POST_STAR_START';
export const POST_STAR__SUCCESS = 'POST_STAR_SUCCESS';
export const POST_STAR__FAIL = 'FETCH_STAR_POST';

export const DELETE_STAR_SUCCESS = 'DELETE_STAR_SUCCESS';
export const DELETE_STAR_FAIL = 'DELETE_STARS_FAIL';

export const RECV_ERROR = 'RECV_ERROR';
export const RECV_DATA = 'RECV_DATA';