export const FETCH_UNIVERSES_START = 'FETCH_UNIVERSES_START';
export const FETCH_UNIVERSES_SUCCESS = 'FETCH_UNIVERSES_SUCCESS';
export const FETCH_UNIVERSES_FAIL = 'FETCH_UNIVERSES_FAIL';

export const FETCH_UNIVERSE_START = 'FETCH_UNIVERSE_START';
export const FETCH_UNIVERSE_SUCCESS = 'FETCH_UNIVERSE_SUCCESS';
export const FETCH_UNIVERSE_FAIL = 'FETCH_UNIVERSE_FAIL';

export const FETCH_STARS_START = 'FETCH_STARS_START';
export const FETCH_STARS_SUCCESS = 'FETCH_STARS_SUCCESS';
export const FETCH_STARS_FAIL = 'FETCH_STARS_FAIL';


export const CLICK_BUTTON = 'CLICK_BUTTON';
export const RECV_ERROR = 'RECV_ERROR';
export const REQ_DATA = 'REQ_DATA';
export const RECV_DATA = 'RECV_DATA';